import { useEffect, useState } from 'react'
import { api } from '../api'
import type { Brand, Competitor } from '../types'

// Competitor B — the ChatGPT-generated "Features marketed & sample marketing"
// part of each analysed competitor (moved out of the Competitors tab).
export function CompetitorFeatures() {
  const [brands, setBrands] = useState<Brand[]>([])
  const [brandId, setBrandId] = useState('')
  const [competitors, setCompetitors] = useState<Competitor[]>([])
  const [viewId, setViewId] = useState('')
  const [loading, setLoading] = useState(false)
  const [pickedCopy, setPickedCopy] = useState<number | null>(null)

  useEffect(() => {
    api.listBrands().then(setBrands)
  }, [])

  useEffect(() => {
    if (!brandId) {
      setCompetitors([])
      return
    }
    setLoading(true)
    api
      .listCompetitors(brandId)
      .then((cs) => setCompetitors(cs.filter((c) => c.status === 'considered')))
      .finally(() => setLoading(false))
  }, [brandId])

  useEffect(() => {
    if (competitors.length === 0) {
      if (viewId) setViewId('')
      return
    }
    if (!competitors.some((c) => c.id === viewId)) {
      const primary = competitors.find((c) => c.is_primary)
      setViewId(primary ? primary.id : competitors[0].id)
    }
  }, [competitors, viewId])

  const selected = competitors.find((c) => c.id === viewId) ?? null
  const features = selected?.analysis?.features ?? []
  const marketingCopy = selected?.analysis?.marketing_copy ?? []
  // Feature pages we fall back to only if the chosen copy has no usable source URL.
  const imgFeatures = features.filter((f) => (f.source || '').startsWith('http'))

  // The Marketing image tracks the CHOSEN marketing copy — default to the first
  // option when the competitor changes so an image always matches a copy.
  useEffect(() => {
    setPickedCopy(marketingCopy.length ? 0 : null)
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [viewId])

  // Show an image for the CHOSEN copy: try the copy's own source page first, then
  // fall back to the competitor's feature pages (which reliably carry real content
  // images — homepages often only expose a flaky og:image), all ranked by the
  // chosen copy's text so the picture illustrates that specific copy.
  const chosenCopy = pickedCopy !== null ? marketingCopy[pickedCopy] : null
  const copyPage = (chosenCopy?.source || '').startsWith('http') ? chosenCopy!.source : ''
  const imgHint = chosenCopy?.copy || imgFeatures[0]?.feature || null
  const imgPages = [copyPage, ...imgFeatures.map((f) => f.source)].filter(
    (p, i, a) => p && a.indexOf(p) === i,
  )


  return (
    <div className="phase-body">
      <header className="phase-head">
        <span className="phase-tag">Competitor B</span>
        <h1>Features marketed &amp; sample marketing</h1>
        <p>
          The features each considered competitor markets, with a sample marketing line and a
          source link — generated by ChatGPT (web search). Run the analysis on the
          <strong> Competitors</strong> tab first.
        </p>
      </header>

      <div className="icp-toolbar">
        <label className="brand-select">
          <span>Brand</span>
          <select value={brandId} onChange={(e) => setBrandId(e.target.value)}>
            <option value="">{brands.length === 0 ? 'No brands yet' : 'Select a brand…'}</option>
            {brands.map((b) => (
              <option key={b.id} value={b.id}>
                {b.name}
              </option>
            ))}
          </select>
        </label>
      </div>

      {!brandId ? (
        <div className="card muted">Select a brand to view its competitors' marketed features.</div>
      ) : loading ? (
        <div className="card muted">Loading…</div>
      ) : competitors.length === 0 ? (
        <div className="card muted">
          No considered competitors yet — shortlist some on the <strong>Competitors</strong> tab.
        </div>
      ) : (
        <section className="card">
          <div className="analysis-picker">
            <label className="brand-select">
              <span>Competitor</span>
              <select value={selected?.id ?? ''} onChange={(e) => setViewId(e.target.value)}>
                {competitors.map((c) => (
                  <option key={c.id} value={c.id}>
                    {c.name}
                    {c.is_primary ? ' ★' : ''}
                    {c.analysis ? '' : ' — not analysed'}
                  </option>
                ))}
              </select>
            </label>
          </div>

          <h4 className="analysis-name">
            {selected?.name}
            {selected?.is_primary && <span className="primary-badge">★ Primary</span>}
          </h4>

          {!selected?.analysis ? (
            <p className="muted">Not analysed yet — run “Analyse” for this competitor on the Competitors tab.</p>
          ) : (
            <>
              <h4>Features marketed &amp; sample marketing</h4>
              {features.length ? (
                <table className="atable feature-table">
                  <thead>
                    <tr><th>Feature</th><th>Sample marketing</th><th>Source</th></tr>
                  </thead>
                  <tbody>
                    {features.map((f, i) => (
                      <tr key={i}>
                        <td>{f.feature || 'NA'}</td>
                        <td>{f.sample_marketing || 'NA'}</td>
                        <td><SourceCell text={f.source} /></td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              ) : (
                <p className="muted">No features found.</p>
              )}

              <h4>Marketing copy (Top 3)</h4>
              {marketingCopy.length ? (
                <div className="copy-options">
                  {marketingCopy.map((c, i) => (
                    <button
                      type="button"
                      key={i}
                      className={`copy-option ${pickedCopy === i ? 'active' : ''}`}
                      onClick={() => setPickedCopy(i)}
                    >
                      <span className="copy-num">{i + 1}</span>
                      <span className="copy-text">{c.copy || 'NA'}</span>
                      <SourceCell text={c.source} />
                    </button>
                  ))}
                </div>
              ) : (
                <p className="muted">No marketing copy found.</p>
              )}

              <h4>Marketing image</h4>
              {pickedCopy === null ? (
                <p className="muted">Pick a marketing copy above to generate its matching image.</p>
              ) : imgPages.length ? (
                <FeatureImage
                  key={pickedCopy}
                  pages={imgPages}
                  hint={imgHint}
                  caption={
                    chosenCopy
                      ? `Matches copy #${pickedCopy + 1}: “${chosenCopy.copy}”`
                      : 'Marketing image'
                  }
                />
              ) : (
                <p className="muted">No source page to pull an image from — try Re-analyse.</p>
              )}
            </>
          )}
        </section>
      )}
    </div>
  )
}

function FeatureImage({ pages, hint, caption }: { pages: string[]; hint: string | null; caption: string }) {
  // Walk the candidate pages in order, advancing whenever a page yields no image
  // URL or the image itself fails to load — so a real image reliably shows.
  const key = pages.join('|') + '::' + (hint || '')
  const [idx, setIdx] = useState(0)
  const [imageUrl, setImageUrl] = useState<string | null>(null)

  useEffect(() => {
    setIdx(0)
    setImageUrl(null)
  }, [key])

  useEffect(() => {
    if (idx >= pages.length) return
    let cancelled = false
    setImageUrl(null)
    const page = pages[idx]
    // `feature` is the backend's ranking hint — here it's the chosen copy's text.
    const q = `page=${encodeURIComponent(page)}${hint ? `&feature=${encodeURIComponent(hint)}` : ''}`
    fetch(`/api/feature-image-url?${q}`)
      .then((r) => (r.ok ? r.json() : Promise.reject(new Error('no image'))))
      .then((d) => { if (!cancelled) setImageUrl(d.image) })
      .catch(() => { if (!cancelled) setIdx((i) => i + 1) }) // no image on this page → next
    return () => { cancelled = true }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [idx, key])

  if (idx >= pages.length) {
    return (
      <p className="muted">
        Couldn't pull an image for this copy — open the{' '}
        <a href={pages[0]} target="_blank" rel="noreferrer">source page</a>.
      </p>
    )
  }
  if (!imageUrl) return <p className="muted">Loading image…</p>

  const page = pages[idx]
  return (
    <figure className="marketing-image">
      <img
        src={`/api/image-proxy?url=${encodeURIComponent(imageUrl)}`}
        alt={caption}
        onError={() => setIdx((i) => i + 1)} // this page's image didn't load → next candidate
      />
      <figcaption className="muted">
        {caption}
        <br />
        Image URL: <a href={imageUrl} target="_blank" rel="noreferrer">{imageUrl}</a>
        <br />
        Found on: <a href={page} target="_blank" rel="noreferrer">{page}</a>
      </figcaption>
    </figure>
  )
}

function SourceCell({ text }: { text: string }) {
  if (!text || text === 'NA') return <span className="muted">NA</span>
  const url = text.match(/https?:\/\/[^\s)]+/)?.[0]
  const label = text.replace(/\s*\(?https?:\/\/[^\s)]+\)?/, '').trim() || 'link'
  if (!url) return <span>{text}</span>
  return (
    <a href={url} target="_blank" rel="noreferrer">{label}</a>
  )
}
