"""competitor is_primary

Revision ID: 009e8f73d989
Revises: 887e094333be
Create Date: 2026-07-07 15:31:11.508687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '009e8f73d989'
down_revision: Union[str, None] = '887e094333be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('competitors', sa.Column('is_primary', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('competitors', 'is_primary')
    # ### end Alembic commands ###
