"""competitor source

Revision ID: 9e43278d6ab2
Revises: 537658c2c31d
Create Date: 2026-07-07 16:43:06.938421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '9e43278d6ab2'
down_revision: Union[str, None] = '537658c2c31d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('competitors', sa.Column('source', sa.String(length=20), server_default='tailored', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('competitors', 'source')
    # ### end Alembic commands ###
