"""persona structured subparts

Revision ID: a0b89ffd7554
Revises: 9a3167465afb
Create Date: 2026-07-04 20:43:44.218715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a0b89ffd7554'
down_revision: Union[str, None] = '9a3167465afb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('personas', sa.Column('user_type', sa.String(length=100), nullable=True))
    op.add_column('personas', sa.Column('business_size', sa.String(length=50), nullable=True))
    op.add_column('personas', sa.Column('region', sa.String(length=100), nullable=True))
    op.add_column('personas', sa.Column('pain_points', sa.Text(), nullable=True))
    op.add_column('personas', sa.Column('current_platforms', sa.Text(), nullable=True))
    op.add_column('personas', sa.Column('main_goal', sa.Text(), nullable=True))
    op.drop_column('personas', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('personas', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('personas', 'main_goal')
    op.drop_column('personas', 'current_platforms')
    op.drop_column('personas', 'pain_points')
    op.drop_column('personas', 'region')
    op.drop_column('personas', 'business_size')
    op.drop_column('personas', 'user_type')
    # ### end Alembic commands ###
