"""competitor analysis jsonb

Revision ID: d7048605b8f7
Revises: 009e8f73d989
Create Date: 2026-07-07 15:50:36.785213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'd7048605b8f7'
down_revision: Union[str, None] = '009e8f73d989'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('competitors', sa.Column('analysis', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('competitors', 'analysis')
    # ### end Alembic commands ###
